---
abstract: 'Named subroutine arguments, with optional type checking'
author:
  - 'The original code (written before September 15, 2004) was written by '
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Getargs::Long
name: Getargs-Long
no_index:
  directory:
    - inc
    - t
requires:
  Log::Agent: 0.105
  perl: 5.005
version: 1.1003
